export const MICRO_SURVEY_STORE: any[] = [
  {
    id: 'ms-seed-1',
    billId: 'ocd-bill/2026-oh-cleveland-ord-882',
    billTitle: 'Slavic Village Stormwater Basin',
    divisionId: 'ocd-division/country:us/state:oh/place:cleveland/ward:12',
    wardNumber: 12,
    residentRole: 'homeowner',
    stance: 'support',
    perceivedCostImpactUSD: -30,
    priorityRating: 9,
    anonymizedFeedback: 'Basement flooding on Fleet Ave has cost us thousands every spring. This is urgent.',
    epsilon: 1.0,
    submittedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'ms-seed-2',
    billId: 'ocd-bill/2026-oh-cleveland-ord-882',
    billTitle: 'Slavic Village Stormwater Basin',
    divisionId: 'ocd-division/country:us/state:oh/place:cleveland/ward:12',
    wardNumber: 12,
    residentRole: 'small_business',
    stance: 'support',
    perceivedCostImpactUSD: -120,
    priorityRating: 8,
    anonymizedFeedback: 'Protects commercial parking and foundation stability for our shop.',
    epsilon: 1.0,
    submittedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'ms-seed-3',
    billId: 'ocd-bill/2026-oh-cleveland-ord-915',
    billTitle: 'Transit-Oriented Parking Minimum Reform',
    divisionId: 'ocd-division/country:us/state:oh/place:cleveland/ward:3',
    wardNumber: 3,
    residentRole: 'renter',
    stance: 'support',
    perceivedCostImpactUSD: -60,
    priorityRating: 8,
    anonymizedFeedback: 'Lower construction mandates reduce developer rents along the W 25th transit corridor.',
    epsilon: 1.0,
    submittedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'ms-seed-4',
    billId: 'ocd-bill/2026-oh-cleveland-ord-915',
    billTitle: 'Transit-Oriented Parking Minimum Reform',
    divisionId: 'ocd-division/country:us/state:oh/place:cleveland/ward:3',
    wardNumber: 3,
    residentRole: 'homeowner',
    stance: 'oppose',
    perceivedCostImpactUSD: 25,
    priorityRating: 6,
    anonymizedFeedback: 'Worried street parking overflow will spill onto residential side streets.',
    epsilon: 1.0,
    submittedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const USER_PROFILES_STORE: Map<string, any> = new Map();
